# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 22, size: 0.062},
    # {id: 0, size: 0.03},
    # {id: 1, size: 0.03},
    # {id: 2, size: 0.03},
    # {id: 3, size: 0.03},
    # {id: 4, size: 0.03},
    # {id: 5, size: 0.03},
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]

tag_bundles:
  [
    {
      name: 'Small Block',
      layout:
      [
        {id: 0, size: 0.03, x: 0.00, y: 0.00, z: 0.02, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
        {id: 1, size: 0.03, x: 0.02, y: 0.00, z: 0.00, qw: 0.7071, qx: 0.0, qy: 0.7071, qz: 0.0},
        {id: 2, size: 0.03, x: 0.00, y: 0.00, z: -0.02, qw: 0.0, qx: 0.0, qy: 1.0, qz: 0.0},
        {id: 3, size: 0.03, x: -0.02, y: 0.00, z: 0.00, qw: 0.7071, qx: 0.0, qy: -0.7071, qz: 0.0},
        {id: 4, size: 0.03, x: 0.00, y: 0.02, z: 0.00, qw: 0.7071, qx: -0.7071, qy: 0.0, qz: 0.0},
        {id: 5, size: 0.03, x: 0.00, y: -0.02, z: 0.00, qw: 0.7071, qx: 0.7071, qy: 0.0, qz: 0.0},
      ]
    }    
  ]